# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Static board evaluation (Rcpp)
#'
#' Returns a centipawn score from white's perspective. Combines material
#' value with piece-square table positional bonuses.
#'
#' @param board_matrix 8x8 NumericMatrix. See Board$encode_for_engine().
#' @return Numeric. Score in centipawns.
#' @export
chess_evaluate <- function(board_matrix) {
    .Call(`_ChessSimulator_chess_evaluate`, board_matrix)
}

#' Generate all pseudo-legal moves for one side (Rcpp)
#'
#' @param board_matrix 8x8 NumericMatrix.
#' @param is_white_int 1 = white, -1 = black.
#' @return Nx2 IntegerMatrix with 1-based (from, to) indices.
#' @export
chess_legal_moves <- function(board_matrix, is_white_int) {
    .Call(`_ChessSimulator_chess_legal_moves`, board_matrix, is_white_int)
}

#' Minimax search entry point (Rcpp)
#'
#' @param board_matrix 8x8 NumericMatrix.
#' @param is_white_int 1 = white to move, -1 = black to move.
#' @param depth Positive integer. Search depth.
#' @return IntegerVector of length 2: c(from_index, to_index), 1-based.
#' @export
chess_minimax <- function(board_matrix, is_white_int, depth) {
    .Call(`_ChessSimulator_chess_minimax`, board_matrix, is_white_int, depth)
}

