# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Static evaluation of a chess position (C++)
#'
#' Scores a position in centipawns from white's point of view: positive means
#' white stands better, negative means black. Combines material (pawn 100,
#' knight 320, bishop 330, rook 500, queen 900) with piece-square table
#' bonuses that reward good placement.
#'
#' @param board_matrix An 8x8 integer matrix from
#'   \code{Board$encode_for_engine()}.
#' @return A single numeric value in centipawns.
#' @export
chess_evaluate <- function(board_matrix) {
    .Call(`_ChessSimulator_chess_evaluate`, board_matrix)
}

#' All legal moves for one side (C++)
#'
#' Generates every legal move: moves that follow the movement rules
#' \emph{and} do not leave the mover's own king in check.
#'
#' @param board_matrix An 8x8 integer matrix from
#'   \code{Board$encode_for_engine()}.
#' @param is_white_int \code{1} for white to move, \code{-1} for black.
#' @return An N x 2 integer matrix; each row is \code{c(from, to)} with
#'   1-based square indices (a1 = 1, h8 = 64). Zero rows means the side to
#'   move is checkmated or stalemated.
#' @export
chess_legal_moves <- function(board_matrix, is_white_int) {
    .Call(`_ChessSimulator_chess_legal_moves`, board_matrix, is_white_int)
}

#' Best move by minimax search with alpha-beta pruning (C++)
#'
#' Searches the game tree to the requested depth and returns the best move for
#' the side to move. Uses alpha-beta pruning with MVV-LVA move ordering, and
#' scores checkmate so that faster mates are preferred.
#'
#' Ties between equally good moves are broken with R's random number stream,
#' so \code{set.seed()} makes engine games reproducible.
#'
#' @param board_matrix An 8x8 integer matrix from
#'   \code{Board$encode_for_engine()}.
#' @param is_white_int \code{1} for white to move, \code{-1} for black.
#' @param depth Search depth in plies. 2 is fast and tactical, 3 is a good
#'   default, 4 is noticeably stronger and still quick.
#' @return An integer vector \code{c(from, to)} with 1-based square indices,
#'   or \code{c(0, 0)} when there are no legal moves.
#' @export
chess_minimax <- function(board_matrix, is_white_int, depth) {
    .Call(`_ChessSimulator_chess_minimax`, board_matrix, is_white_int, depth)
}

#' Move generator self-test (perft)
#'
#' Counts leaf nodes in the game tree at a given depth. This is the standard
#' correctness test for a chess move generator: from the starting position the
#' counts must be 20, 400, 8902 and 197281 for depths 1 to 4. If even one
#' illegal move is generated, or one legal move missed, the counts break.
#'
#' @param board_matrix An 8x8 integer matrix from
#'   \code{Board$encode_for_engine()}.
#' @param is_white_int \code{1} for white to move, \code{-1} for black.
#' @param depth Depth in plies. Keep to 4 or less; the count grows fast.
#' @return The number of leaf nodes, as a numeric value.
#' @export
chess_perft <- function(board_matrix, is_white_int, depth) {
    .Call(`_ChessSimulator_chess_perft`, board_matrix, is_white_int, depth)
}

